dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE clinica_etsii;'
script: 
  - mvn test sonar:sonar -Dspring-boot.run.profiles=mysql-travis